stages:
  - build

build:
  stage: build
  image: r1ddl3m37h15/openjdk11-build:v1
  tags:
    - docker, linux
  only:
    refs:
      - branches
  script:
    - echo info $(date) $(hostname) $(whoami) $(pwd)
    - javac -version
    - env | sort
    - ant
