stages:
  - build

build:
  stage: build
  image: r1ddl3m37h15/jdk8-ant:v2
  tags:
    - docker, linux
  only:
    refs:
      - branches
  script:
    - echo info $(date) $(hostname) $(whoami) $(pwd)
    - javac -version
    - env
    - ant
